application: puppy-r
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /font
  static_dir: static/font

- url: /fonts
  static_dir: static/fonts

- url: /media
  static_dir: static/media

- url: /js
  static_dir: static/js

- url: /.*
  script: plantilla.app

  #url:http://puppy-r.appspot.com/
